# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "ko-KR"
title                    : "테디노트"
title_separator          : "-"
subtitle                 : "데이터와 인공지능을 좋아하는 개발자 노트"
name                     : "테디노트"
description              : "데이터와 인공지능을 좋아하는 개발자 노트"
url                      : "https://teddylee777.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "teddylee777/minimal-mistakes"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
breadcrumbs              : true
words_per_minute         : 200

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
